# kubectl apply -f paul-poma-11-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: paul-poma-11-secret
  namespace: paul-poma-11-namespace
type: Opaque
data:
  DATABASE_NAME: QW5nb21hVG91cnM=   # en Base64
  DATABASE_URI: bW9uZ29kYitzcnY6Ly9jaXJvcG9tYV9kYjp5WjJ1SWV6a2QycVI0S09YQGNsdXN0ZXIwLmRodWJvcXkubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==   # en Base64

#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode