# kubectl apply -f paul-poma-11-service.yml
apiVersion: v1
kind: Service
metadata:
  name: paul-poma-11-service
  namespace: paul-poma-11-namespace
spec:
  type: NodePort      #30000-32767  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
  - port: 30001       # Puerto que el Service expondrá
    targetPort: 8086  # Puerto en el contenedor donde tu aplicación escucha
    nodePort: 30001   # Puerto asignado en el nodo, opcional
  selector:
    app: paul-poma-11-deployment  # Debe coincidir con las etiquetas del Deployment